spring.application.name=claims-processing-system
spring.datasource.url=jdbc:postgresql://localhost:5432/claims_processing_db
spring.datasource.username=john
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true